### ISSUE TITLE
用toolbox游戏安装闪退，疑似MelonLoader版本问题

### ISSUE THREAD

**Issue by yangkile** [LocalizeLimbusCompany/LLC_MOD_Toolbox#15]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

安装成功，但是游戏启动时候会报错
目录地址和已安装的目录不合，不在D:\a\
[00:58:53.453] [MelonStartScreen] Initializing...
[00:58:54.064] Loading Il2CppAssemblyGenerator...
[00:58:54.829] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at MelonLoader.Il2CppAssemblyGenerator.Packages.Cpp2IL.GetFastnetNode() in D:\a\MelonLoader-LLC\MelonLoader-LLC\Dependencies\Il2CppAssemblyGenerator\Packages\Cpp2IL.cs:line 129
   at MelonLoader.Il2CppAssemblyGenerator.Packages.Cpp2IL..ctor() in D:\a\MelonLoader-LLC\MelonLoader-LLC\Dependencies\Il2CppAssemblyGenerator\Packages\Cpp2IL.cs:line 18
   at MelonLoader.Il2CppAssemblyGenerator.Core.Run() in D:\a\MelonLoader-LLC\MelonLoader-LLC\Dependencies\Il2CppAssemblyGenerator\Core.cs:line 55
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at MelonLoader.Modules.MelonModule.SendMessage(String name, Object[] arguments) in D:\a\MelonLoader-LLC\MelonLoader-LLC\MelonLoader\Modules\MelonModule.cs:line 110
   at MelonLoader.InternalUtils.Il2CppAssemblyGenerator.Run() in D:\a\MelonLoader-LLC\MelonLoader-LLC\MelonLoader\InternalUtils\Il2CppAssemblyGenerator.cs:line 27
   at MelonLoader.Core.Il2CppGameSetup() in D:\a\MelonLoader-LLC\MelonLoader-LLC\MelonLoader\Core.cs:line 111
   at MelonLoader.MelonStartScreen.Core.<>c__DisplayClass17_0.<StartFunction>b__0() in D:\a\MelonLoader-LLC\MelonLoader-LLC\Dependencies\MelonStartScreen\Core.cs:line 165
   at System.Threading.Thread.StartCallback()
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at MelonLoader.Il2CppAssemblyGenerator.Packages.Cpp2IL.GetFastnetNode() in D:\a\MelonLoader-LLC\MelonLoader-LLC\Dependencies\Il2CppAssemblyGenerator\Packages\Cpp2IL.cs:line 129
   at MelonLoader.Il2CppAssemblyGenerator.Packages.Cpp2IL..ctor() in D:\a\MelonLoader-LLC\MelonLoader-LLC\Dependencies\Il2CppAssemblyGenerator\Packages\Cpp2IL.cs:line 18
   at MelonLoader.Il2CppAssemblyGenerator.Core.Run() in D:\a\MelonLoader-LLC\MelonLoader-LLC\Dependencies\Il2CppAssemblyGenerator\Core.cs:line 55
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at MelonLoader.Modules.MelonModule.SendMessage(String name, Object[] arguments) in D:\a\MelonLoader-LLC\MelonLoader-LLC\MelonLoader\Modules\MelonModule.cs:line 110
   at MelonLoader.InternalUtils.Il2CppAssemblyGenerator.Run() in D:\a\MelonLoader-LLC\MelonLoader-LLC\MelonLoader\InternalUtils\Il2CppAssemblyGenerator.cs:line 27
   at MelonLoader.Core.Il2CppGameSetup() in D:\a\MelonLoader-LLC\MelonLoader-LLC\MelonLoader\Core.cs:line 111
   at MelonLoader.MelonStartScreen.Core.<>c__DisplayClass17_0.<StartFunction>b__0() in D:\a\MelonLoader-LLC\MelonLoader-LLC\Dependencies\MelonStartScreen\Core.cs:line 165

### 日志文件

[2023/7/5 0:41:24] LLCToolbox is loading.
[2023/7/5 0:41:24] Button is Disabled.
[2023/7/5 0:41:24] Getting Fastest Node...
[2023/7/5 0:41:24] Ping the Node...
[2023/7/5 0:41:24] Ping: github.com ...
[2023/7/5 0:41:24] github.com 's Roundtriptime is: 116ms.
[2023/7/5 0:41:24] Ping: limbus.determination.top ...
[2023/7/5 0:41:25] limbus.determination.top 's Roundtriptime is: 321ms.
[2023/7/5 0:41:25] Ping: llc.determination.top ...
[2023/7/5 0:41:25] llc.determination.top 's Roundtriptime is: 286ms.
[2023/7/5 0:41:25] Ping: dl.determination.top ...
[2023/7/5 0:41:25] dl.determination.top 's Roundtriptime is: 78ms.
[2023/7/5 0:41:25] Done. The Fastest Node is: dl.determination.top. Roundtriptime is: 78ms.
[2023/7/5 0:41:25] Done. The Fastest Node is: dl.determination.top
[2023/7/5 0:41:25] Check the Installer's Update.
[2023/7/5 0:41:25] Open Github API.
[2023/7/5 0:41:31] Crash - Check Installer's Update
[2023/7/5 0:41:31] .NET Framework 4.8.4644.0
[2023/7/5 0:41:31] Check the Dotnet Ver.
[2023/7/5 0:41:31] User have dotnet 6.0.
[2023/7/5 0:41:31] Check User System.
[2023/7/5 0:41:31] User system is Windows10 or Windows11.
[2023/7/5 0:41:31] Find Limbus Company Dir.
[2023/7/5 0:41:31] Use the auto select way.
[2023/7/5 0:41:31] Find Limbus Company Dir.
[2023/7/5 0:41:31] Find Limbus Company Dir is done.
[2023/7/5 0:41:31] Button is Enabled.
[2023/7/5 0:45:55] Start Install Mod.
[2023/7/5 0:45:55] Download MelonLoader.
[2023/7/5 0:45:55] Button is Disabled.
[2023/7/5 0:45:55] Use MFL.
[2023/7/5 0:45:55] Downloading MFL...
[2023/7/5 0:45:55] LimbusCompanyDir: E:\Steam\steamapps\common\Limbus Company
[2023/7/5 0:45:55] cant find melonloader. start installing
[2023/7/5 0:45:56] MelonLoaderZipPath: E:\Steam\steamapps\common\Limbus Company\ML_LLC_v0.6.3.zip
[2023/7/5 0:45:56] Download the File from: https://dl.determination.top/files/ML_LLC_v0.6.3.zip
[2023/7/5 0:48:38] start Extract zip.
[2023/7/5 0:48:39] Extract zip...
[2023/7/5 0:48:39] MFL is done.
[2023/7/5 0:48:39] Downloading tmpchinese...
[2023/7/5 0:48:39] create moddir.
[2023/7/5 0:48:40] Download the File from: https://dl.determination.top/files/tmpchinesefont.7z
[2023/7/5 0:51:06] Extract zip...
[2023/7/5 0:51:06] download tmpchinese is done.
[2023/7/5 0:51:06] download mod...
[2023/7/5 0:51:08] Download the File from: https://dl.determination.top/files/LimbusLocalize_FullPack.7z
[2023/7/5 0:51:16] Extract zip...
[2023/7/5 0:51:17] Install is done!
[2023/7/5 0:51:18] Button is Enabled.

**Comment by ZengXiaoPi** [comment]
网络问题，尝试关闭MelonLoader For LLC，并在melonloader初次启动/游戏更新时加速github。
