### ISSUE TITLE
汉化显示错误

### ISSUE THREAD

**Issue by fivetreesgantai** [LocalizeLimbusCompany/LLC_MOD_Toolbox#72]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

进入游戏时标题画面与加载画面显示汉化正常，进入游戏后为英文显示，之后打开工具进行卸载重装报错，等待四五分钟后卸载重装成功，但是问题没有解决

### 日志文件

[Error  :Il2CppInterop] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.MissingMethodException: Method not found: 'Il2CppSystem.ValueTuple`2<!!0,DelegateEvent> Addressable.AddressableManager.LoadAssetSync(System.String, System.String, UnityEngine.Transform, System.String)'.
   at LimbusLocalize.LCB_Chinese_Font.LoadRemote2()
   at LimbusLocalize.LCB_Chinese_Font.<>c__DisplayClass12_1.<EGOVoiceJsonDataListInit>b__0(LocalizeTextDataRoot`1 data)
   at (il2cpp delegate trampoline) System.Void_System.Action`1[[LocalizeTextDataRoot`1[[TextData_EGOVoice, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]], Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]]_LocalizeTextDataRoot`1[[TextData_EGOVoice, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]](IntPtr , IntPtr , Il2CppMethodInfo* )

### 截图

![IMG_20241002_113105](https://github.com/user-attachments/assets/04d33e10-dcb8-430e-8092-2c9cc358d03b)
![IMG_20241002_113105](https://github.com/user-attachments/assets/4e9d1142-43b5-4b8d-8c4d-79c50ea38c5d)

**Comment by fivetreesgantai** [comment]
不好意思，电脑卡了一下截图传了两份（哭）

**Comment by lsyandyfy** [comment]
有类似的问题，小贴士、loading整活汉化正常，进入游戏后界面和绝大部分文本仍为英文（0协通知为中文），已经尝试过用工具箱卸载重装/删除根目录下四个文件重新解压/重装游戏与汉化/文件覆盖的方式，仍未解决
游戏中控制台报错如下
[Error  :Il2CppInterop] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.MissingMethodException: Method not found: 'Il2CppSystem.ValueTuple`2<!!0,DelegateEvent> Addressable.AddressableManager.LoadAssetSync(System.String, System.String, UnityEngine.Transform, System.String)'.
   at LimbusLocalize.LCB_Chinese_Font.LoadRemote2()
   at LimbusLocalize.LCB_Chinese_Font.<>c__DisplayClass12_1.<EGOVoiceJsonDataListInit>b__0(LocalizeTextDataRoot`1 data)
   at (il2cpp delegate trampoline) System.Void_System.Action`1[[LocalizeTextDataRoot`1[[TextData_EGOVoice, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]], Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]]_LocalizeTextDataRoot`1[[TextData_EGOVoice, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]](IntPtr , IntPtr , Il2CppMethodInfo* )

**Comment by lsyandyfy** [comment]
> 有类似的问题，小贴士、loading整活汉化正常，进入游戏后界面和绝大部分文本仍为英文（0协通知为中文），已经尝试过用工具箱卸载重装/删除根目录下四个文件重新解压/重装游戏与汉化/文件覆盖的方式，仍未解决 游戏中控制台报错如下 [Error :Il2CppInterop] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.MissingMethodException: Method not found: 'Il2CppSystem.ValueTuple`2<!!0,DelegateEvent> Addressable.AddressableManager.LoadAssetSync(System.String, System.String, UnityEngine.Transform, System.String)'. at LimbusLocalize.LCB_Chinese_Font.LoadRemote2() at LimbusLocalize.LCB_Chinese_Font.<>c__DisplayClass12_1.<EGOVoiceJsonDataListInit>b__0(LocalizeTextDataRoot`1 data) at (il2cpp delegate trampoline) System.Void_System.Action`1[[LocalizeTextDataRoot`1[[TextData_EGOVoice, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]], Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]]_LocalizeTextDataRoot`1[[TextData_EGOVoice, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]](IntPtr , IntPtr , Il2CppMethodInfo* )

又同时发现剧情播放只会出现ui，但黑屏无内容

**Comment by N071** [comment]
此问题应当已经解决，请检查并下载最新版本，感谢反馈
