### ISSUE TITLE
点击开始游戏后进入游戏控制台报错，汉化部分失败（加载界面是中文，进游戏后游戏其他内容是英文）

### ISSUE THREAD

**Issue by 114514-GitHu** [LocalizeLimbusCompany/LLC_MOD_Toolbox#73]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

报错[Error  :Il2CppInterop] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.MissingMethodException: Method not found: 'Il2CppSystem.ValueTuple`2<!!0,DelegateEvent> Addressable.AddressableManager.LoadAssetSync(System.String, System.String, UnityEngine.Transform, System.String)'.
   at LimbusLocalize.LCB_Chinese_Font.LoadRemote2()
   at LimbusLocalize.LCB_Chinese_Font.<>c__DisplayClass12_1.<EGOVoiceJsonDataListInit>b__0(LocalizeTextDataRoot`1 data)
   at (il2cpp delegate trampoline) System.Void_System.Action`1[[LocalizeTextDataRoot`1[[TextData_EGOVoice, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]], Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]]_LocalizeTextDataRoot`1[[TextData_EGOVoice, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]](IntPtr , IntPtr , Il2CppMethodInfo* ) 尝试·重新安装和使用管理员启动无效

### 日志文件

[Player(游戏日志).log](https://github.com/user-attachments/files/17230513/Player.log)

### 截图

![微信截图_20241002220208](https://github.com/user-attachments/assets/0a89dc7c-6f7e-4b88-9e7c-38c03ed27802)
![微信截图_20241002220221](https://github.com/user-attachments/assets/286276ee-9f4c-48c8-b559-6fafa9812e7a)

**Comment by 114514-GitHu** [comment]
[Latest(框架日志).log](https://github.com/user-attachments/files/17230532/Latest.log)

**Comment by 114514-GitHu** [comment]
工具箱用不了了现在重装模组跳错误，现在手动重装了一遍汉化就正常了，问题已经解决

**Comment by ZengXiaoPi** [comment]
主仓库重复议题

**Comment by 114514-GitHu** [comment]
请问“主仓库重复议题”是什么意思谢谢

**Comment by ZengXiaoPi** [comment]
https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/issues/275

**Comment by 114514-GitHu** [comment]
知道了
