### ISSUE TITLE
自动安装检测到游戏正在运行后，点击取消，显示的"正在安装"并不会变回"开始安装"

### ISSUE THREAD

**Issue by 3cxc** [LocalizeLimbusCompany/LLC_MOD_Toolbox#92]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在选择自动安装并点击开始安装后，若游戏正在运行，则会弹出警告。
此时点击取消后，显示的"正在安装"并不会变回"开始安装"，且无法重新进行自动安装(只能重启程序)

### 日志文件

记录时间：2024-11-23 22:39:07,979 日志级别：INFO  - 描述：—————新日志分割线—————
记录时间：2024-11-23 22:39:07,985 日志级别：INFO  - 描述：工具箱已进入加载流程。
记录时间：2024-11-23 22:39:07,985 日志级别：INFO  - 描述：We have a lift off.
记录时间：2024-11-23 22:39:07,985 日志级别：INFO  - 描述：WPF架构工具箱 版本：1.0.2 。
记录时间：2024-11-23 22:39:09,135 日志级别：INFO  - 描述：刷新页面状态中。
记录时间：2024-11-23 22:39:09,146 日志级别：INFO  - 描述：刷新页面状态完成。
记录时间：2024-11-23 22:39:09,983 日志级别：INFO  - 描述：正在检查工具箱更新。
记录时间：2024-11-23 22:39:10,120 日志级别：INFO  - 描述：加载程序配置。
记录时间：2024-11-23 22:39:10,132 日志级别：INFO  - 描述：跳过路径检查：False
记录时间：2024-11-23 22:39:10,132 日志级别：INFO  - 描述：路径：
记录时间：2024-11-23 22:39:10,224 日志级别：INFO  - 描述：使用自动查找边狱公司方法。
记录时间：2024-11-23 22:39:10,304 日志级别：ERROR - 描述：出现了问题：
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at LLC_MOD_Toolbox.MainWindow.FindlimbusCompanyDirectory() in C:\Users\17032\source\repos\LLC_MOD_Toolbox\MainWindow.xaml.cs:line 689
记录时间：2024-11-23 22:39:10,777 日志级别：INFO  - 描述：最新安装器tag：1.0.2
记录时间：2024-11-23 22:39:10,777 日志级别：INFO  - 描述：没有更新。
记录时间：2024-11-23 22:39:19,935 日志级别：ERROR - 描述：未能找到 Limbus Company 目录，手动选择模式。
记录时间：2024-11-23 22:39:57,031 日志级别：INFO  - 描述：找到了正确目录。
记录时间：2024-11-23 22:39:57,033 日志级别：INFO  - 描述：改变跳过路径检查配置，Value：True
记录时间：2024-11-23 22:39:57,059 日志级别：INFO  - 描述：配置文件更新完成。
记录时间：2024-11-23 22:39:57,059 日志级别：INFO  - 描述：改变边狱公司路径配置，Value：D:\SteamLibrary\steamapps\common\Limbus Company
记录时间：2024-11-23 22:39:57,062 日志级别：INFO  - 描述：配置文件更新完成。
记录时间：2024-11-23 22:39:57,062 日志级别：INFO  - 描述：边狱公司路径：D:\SteamLibrary\steamapps\common\Limbus Company
记录时间：2024-11-23 22:39:57,143 日志级别：INFO  - 描述：加载流程完成。
记录时间：2024-11-23 22:40:30,978 日志级别：INFO  - 描述：—————新日志分割线—————
记录时间：2024-11-23 22:40:30,986 日志级别：INFO  - 描述：工具箱已进入加载流程。
记录时间：2024-11-23 22:40:30,986 日志级别：INFO  - 描述：We have a lift off.
记录时间：2024-11-23 22:40:30,986 日志级别：INFO  - 描述：WPF架构工具箱 版本：1.0.2 。
记录时间：2024-11-23 22:40:31,117 日志级别：INFO  - 描述：刷新页面状态中。
记录时间：2024-11-23 22:40:31,120 日志级别：INFO  - 描述：刷新页面状态完成。
记录时间：2024-11-23 22:40:31,417 日志级别：INFO  - 描述：正在检查工具箱更新。
记录时间：2024-11-23 22:40:31,475 日志级别：INFO  - 描述：加载程序配置。
记录时间：2024-11-23 22:40:31,482 日志级别：INFO  - 描述：跳过路径检查：True
记录时间：2024-11-23 22:40:31,482 日志级别：INFO  - 描述：路径：D:\SteamLibrary\steamapps\common\Limbus Company
记录时间：2024-11-23 22:40:31,493 日志级别：INFO  - 描述：跳过检查路径。
记录时间：2024-11-23 22:40:31,493 日志级别：INFO  - 描述：边狱公司路径：D:\SteamLibrary\steamapps\common\Limbus Company
记录时间：2024-11-23 22:40:31,496 日志级别：INFO  - 描述：加载流程完成。
记录时间：2024-11-23 22:40:31,980 日志级别：INFO  - 描述：最新安装器tag：1.0.2
记录时间：2024-11-23 22:40:31,980 日志级别：INFO  - 描述：没有更新。
记录时间：2024-11-23 22:40:35,777 日志级别：INFO  - 描述：刷新页面状态中。
记录时间：2024-11-23 22:40:35,777 日志级别：INFO  - 描述：刷新页面状态完成。
记录时间：2024-11-23 22:40:37,200 日志级别：INFO  - 描述：打开了网址：https://www.zeroasso.top/docs/installer/nodes
记录时间：2024-11-23 22:40:42,200 日志级别：INFO  - 描述：打开了网址：https://www.zeroasso.top/docs/installer/nodes
记录时间：2024-11-23 22:40:48,888 日志级别：INFO  - 描述：打开了网址：https://www.zeroasso.top/docs/installer/nodes
记录时间：2024-11-23 22:42:07,896 日志级别：INFO  - 描述：刷新页面状态中。
记录时间：2024-11-23 22:42:07,896 日志级别：INFO  - 描述：刷新页面状态完成。
记录时间：2024-11-23 22:42:44,855 日志级别：INFO  - 描述：打开了网址：https://www.zeroasso.top/docs/installer/nodes
记录时间：2024-11-23 22:42:57,416 日志级别：INFO  - 描述：刷新页面状态中。
记录时间：2024-11-23 22:42:57,416 日志级别：INFO  - 描述：刷新页面状态完成。
记录时间：2024-11-23 22:43:01,464 日志级别：INFO  - 描述：刷新页面状态中。
记录时间：2024-11-23 22:43:01,465 日志级别：INFO  - 描述：刷新页面状态完成。
记录时间：2024-11-23 22:43:03,136 日志级别：INFO  - 描述：刷新页面状态中。
记录时间：2024-11-23 22:43:03,136 日志级别：INFO  - 描述：刷新页面状态完成。
记录时间：2024-11-23 22:43:04,071 日志级别：INFO  - 描述：刷新页面状态中。
记录时间：2024-11-23 22:43:04,072 日志级别：INFO  - 描述：刷新页面状态完成。
记录时间：2024-11-23 22:43:27,711 日志级别：INFO  - 描述：打开了网址：https://www.zeroasso.top/docs/installer/nodes
记录时间：2024-11-23 22:45:20,991 日志级别：INFO  - 描述：打开了网址：https://www.zeroasso.top/docs/installer/nodes
记录时间：2024-11-23 22:46:12,681 日志级别：INFO  - 描述：刷新页面状态中。
记录时间：2024-11-23 22:46:12,681 日志级别：INFO  - 描述：刷新页面状态完成。
记录时间：2024-11-23 22:46:13,449 日志级别：INFO  - 描述：刷新页面状态中。
记录时间：2024-11-23 22:46:13,449 日志级别：INFO  - 描述：刷新页面状态完成。
记录时间：2024-11-23 22:46:13,936 日志级别：INFO  - 描述：刷新页面状态中。
记录时间：2024-11-23 22:46:13,937 日志级别：INFO  - 描述：刷新页面状态完成。
记录时间：2024-11-23 22:46:18,328 日志级别：INFO  - 描述：刷新页面状态中。
记录时间：2024-11-23 22:46:18,329 日志级别：INFO  - 描述：刷新页面状态完成。
记录时间：2024-11-23 22:46:20,089 日志级别：INFO  - 描述：刷新页面状态中。
记录时间：2024-11-23 22:46:20,089 日志级别：INFO  - 描述：刷新页面状态完成。
记录时间：2024-11-23 22:46:23,337 日志级别：INFO  - 描述：刷新页面状态中。
记录时间：2024-11-23 22:46:23,337 日志级别：INFO  - 描述：刷新页面状态完成。
记录时间：2024-11-23 22:46:23,337 日志级别：INFO  - 描述：开始安装。
记录时间：2024-11-23 22:46:23,337 日志级别：INFO  - 描述：**********安装信息打印**********
记录时间：2024-11-23 22:46:23,337 日志级别：INFO  - 描述：本次安装信息：
记录时间：2024-11-23 22:46:23,337 日志级别：INFO  - 描述：是否使用Github：：False
记录时间：2024-11-23 22:46:23,338 日志级别：INFO  - 描述：是否使用Mirror Github：：False
记录时间：2024-11-23 22:46:23,338 日志级别：INFO  - 描述：Limbus公司目录：：空
记录时间：2024-11-23 22:46:23,338 日志级别：INFO  - 描述：Limbus公司游戏目录：：空
记录时间：2024-11-23 22:46:23,338 日志级别：INFO  - 描述：节点列表数量：：6
记录时间：2024-11-23 22:46:23,338 日志级别：INFO  - 描述：使用节点：：空
记录时间：2024-11-23 22:46:23,338 日志级别：INFO  - 描述：灰度测试状态：：False
记录时间：2024-11-23 22:46:23,338 日志级别：INFO  - 描述：**********安装信息打印**********
记录时间：2024-11-23 22:46:23,344 日志级别：WARN  - 描述：LimbusCompany仍然开启。
记录时间：2024-11-23 22:46:32,880 日志级别：INFO  - 描述：刷新页面状态中。
记录时间：2024-11-23 22:46:32,880 日志级别：INFO  - 描述：刷新页面状态完成。
记录时间：2024-11-23 22:46:38,736 日志级别：INFO  - 描述：刷新页面状态中。
记录时间：2024-11-23 22:46:38,736 日志级别：INFO  - 描述：刷新页面状态完成。
记录时间：2024-11-23 22:46:47,666 日志级别：INFO  - 描述：—————新日志分割线—————
记录时间：2024-11-23 22:46:47,674 日志级别：INFO  - 描述：工具箱已进入加载流程。
记录时间：2024-11-23 22:46:47,674 日志级别：INFO  - 描述：We have a lift off.
记录时间：2024-11-23 22:46:47,674 日志级别：INFO  - 描述：WPF架构工具箱 版本：1.0.2 。
记录时间：2024-11-23 22:46:47,800 日志级别：INFO  - 描述：刷新页面状态中。
记录时间：2024-11-23 22:46:47,803 日志级别：INFO  - 描述：刷新页面状态完成。
记录时间：2024-11-23 22:46:48,073 日志级别：INFO  - 描述：正在检查工具箱更新。
记录时间：2024-11-23 22:46:48,116 日志级别：INFO  - 描述：加载程序配置。
记录时间：2024-11-23 22:46:48,122 日志级别：INFO  - 描述：跳过路径检查：True
记录时间：2024-11-23 22:46:48,122 日志级别：INFO  - 描述：路径：D:\SteamLibrary\steamapps\common\Limbus Company
记录时间：2024-11-23 22:46:48,130 日志级别：INFO  - 描述：跳过检查路径。
记录时间：2024-11-23 22:46:48,131 日志级别：INFO  - 描述：边狱公司路径：D:\SteamLibrary\steamapps\common\Limbus Company
记录时间：2024-11-23 22:46:48,133 日志级别：INFO  - 描述：加载流程完成。
记录时间：2024-11-23 22:46:48,720 日志级别：INFO  - 描述：最新安装器tag：1.0.2
记录时间：2024-11-23 22:46:48,720 日志级别：INFO  - 描述：没有更新。
记录时间：2024-11-23 22:47:02,530 日志级别：INFO  - 描述：刷新页面状态中。
记录时间：2024-11-23 22:47:02,530 日志级别：INFO  - 描述：刷新页面状态完成。
记录时间：2024-11-23 22:47:02,530 日志级别：INFO  - 描述：开始安装。
记录时间：2024-11-23 22:47:02,530 日志级别：INFO  - 描述：**********安装信息打印**********
记录时间：2024-11-23 22:47:02,530 日志级别：INFO  - 描述：本次安装信息：
记录时间：2024-11-23 22:47:02,530 日志级别：INFO  - 描述：是否使用Github：：False
记录时间：2024-11-23 22:47:02,530 日志级别：INFO  - 描述：是否使用Mirror Github：：False
记录时间：2024-11-23 22:47:02,531 日志级别：INFO  - 描述：Limbus公司目录：：空
记录时间：2024-11-23 22:47:02,531 日志级别：INFO  - 描述：Limbus公司游戏目录：：空
记录时间：2024-11-23 22:47:02,531 日志级别：INFO  - 描述：节点列表数量：：6
记录时间：2024-11-23 22:47:02,531 日志级别：INFO  - 描述：使用节点：：空
记录时间：2024-11-23 22:47:02,531 日志级别：INFO  - 描述：灰度测试状态：：False
记录时间：2024-11-23 22:47:02,531 日志级别：INFO  - 描述：**********安装信息打印**********
记录时间：2024-11-23 22:47:02,537 日志级别：WARN  - 描述：LimbusCompany仍然开启。
记录时间：2024-11-23 22:48:13,212 日志级别：INFO  - 描述：—————新日志分割线—————
记录时间：2024-11-23 22:48:13,219 日志级别：INFO  - 描述：工具箱已进入加载流程。
记录时间：2024-11-23 22:48:13,219 日志级别：INFO  - 描述：We have a lift off.
记录时间：2024-11-23 22:48:13,219 日志级别：INFO  - 描述：WPF架构工具箱 版本：1.0.2 。
记录时间：2024-11-23 22:48:13,346 日志级别：INFO  - 描述：刷新页面状态中。
记录时间：2024-11-23 22:48:13,349 日志级别：INFO  - 描述：刷新页面状态完成。
记录时间：2024-11-23 22:48:13,633 日志级别：INFO  - 描述：正在检查工具箱更新。
记录时间：2024-11-23 22:48:13,681 日志级别：INFO  - 描述：加载程序配置。
记录时间：2024-11-23 22:48:13,686 日志级别：INFO  - 描述：跳过路径检查：True
记录时间：2024-11-23 22:48:13,686 日志级别：INFO  - 描述：路径：D:\SteamLibrary\steamapps\common\Limbus Company
记录时间：2024-11-23 22:48:13,696 日志级别：INFO  - 描述：跳过检查路径。
记录时间：2024-11-23 22:48:13,696 日志级别：INFO  - 描述：边狱公司路径：D:\SteamLibrary\steamapps\common\Limbus Company
记录时间：2024-11-23 22:48:13,698 日志级别：INFO  - 描述：加载流程完成。
记录时间：2024-11-23 22:48:14,187 日志级别：INFO  - 描述：最新安装器tag：1.0.2
记录时间：2024-11-23 22:48:14,188 日志级别：INFO  - 描述：没有更新。
记录时间：2024-11-23 22:48:15,307 日志级别：INFO  - 描述：刷新页面状态中。
记录时间：2024-11-23 22:48:15,308 日志级别：INFO  - 描述：刷新页面状态完成。
记录时间：2024-11-23 22:48:15,308 日志级别：INFO  - 描述：开始安装。
记录时间：2024-11-23 22:48:15,308 日志级别：INFO  - 描述：**********安装信息打印**********
记录时间：2024-11-23 22:48:15,308 日志级别：INFO  - 描述：本次安装信息：
记录时间：2024-11-23 22:48:15,308 日志级别：INFO  - 描述：是否使用Github：：False
记录时间：2024-11-23 22:48:15,308 日志级别：INFO  - 描述：是否使用Mirror Github：：False
记录时间：2024-11-23 22:48:15,308 日志级别：INFO  - 描述：Limbus公司目录：：空
记录时间：2024-11-23 22:48:15,308 日志级别：INFO  - 描述：Limbus公司游戏目录：：空
记录时间：2024-11-23 22:48:15,308 日志级别：INFO  - 描述：节点列表数量：：6
记录时间：2024-11-23 22:48:15,308 日志级别：INFO  - 描述：使用节点：：空
记录时间：2024-11-23 22:48:15,308 日志级别：INFO  - 描述：灰度测试状态：：False
记录时间：2024-11-23 22:48:15,308 日志级别：INFO  - 描述：**********安装信息打印**********
记录时间：2024-11-23 22:48:15,313 日志级别：WARN  - 描述：LimbusCompany仍然开启。
记录时间：2024-11-23 22:50:25,553 日志级别：INFO  - 描述：刷新页面状态中。
记录时间：2024-11-23 22:50:25,553 日志级别：INFO  - 描述：刷新页面状态完成。
记录时间：2024-11-23 22:50:25,977 日志级别：INFO  - 描述：刷新页面状态中。
记录时间：2024-11-23 22:50:25,977 日志级别：INFO  - 描述：刷新页面状态完成。
记录时间：2024-11-23 22:50:26,976 日志级别：INFO  - 描述：刷新页面状态中。
记录时间：2024-11-23 22:50:26,977 日志级别：INFO  - 描述：刷新页面状态完成。
记录时间：2024-11-23 22:50:27,770 日志级别：INFO  - 描述：刷新页面状态中。
记录时间：2024-11-23 22:50:27,770 日志级别：INFO  - 描述：刷新页面状态完成。
记录时间：2024-11-23 22:51:02,282 日志级别：INFO  - 描述：刷新页面状态中。
记录时间：2024-11-23 22:51:02,283 日志级别：INFO  - 描述：刷新页面状态完成。
记录时间：2024-11-23 22:51:02,616 日志级别：INFO  - 描述：刷新页面状态中。
记录时间：2024-11-23 22:51:02,616 日志级别：INFO  - 描述：刷新页面状态完成。
记录时间：2024-11-23 22:51:11,000 日志级别：INFO  - 描述：刷新页面状态中。
记录时间：2024-11-23 22:51:11,000 日志级别：INFO  - 描述：刷新页面状态完成。
记录时间：2024-11-23 22:51:11,370 日志级别：INFO  - 描述：刷新页面状态中。
记录时间：2024-11-23 22:51:11,370 日志级别：INFO  - 描述：刷新页面状态完成。

### 还有别的吗？

网络出问题了没法上传文件，只好把Log日志直接贴出来了(

**Comment by N071** [comment]
非常感谢，本问题会被修复。
